### ISSUE TITLE
Open to contributions or not open to contributions?

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/Box2D#20]
Generally speaking, I want this project to be open to taking pull requests. I'm not certain how to answer this more specifically however. 

A problem I can foresee with taking pull requests, is that this project is in an *alpha* state in my opinion. I have some major refactoring work that I intend to be pushing to the project where fundamental designs change. I do try and ensure that nothing gets pushed that breaks compiles though.

Comparatively speaking, I think that I'm more comfortable right now considering pull requests for the Testbed or Unit Test portions of the code than the main library code.

Note that I won't take any pull requests that don't appear to follow proper guidelines for appropriately handling copyrights and licensing. If you modify files that you want to be considered for pulling, it's my understanding that the appropriate handling means that you'll have to maintain the project's license and you'll have to note in the header that you've modified the code and how you can be contacted.

IANAL however and I am open to feedback and refinement of this.

**Comment by JesseTG** [comment]
Why not write up a CLA and require contributors to sign it?

**Comment by louis-langholtz** [comment]
@JesseTG I like your idea!

Does GitHub support a CLA strategy for individual OpenSource projects? I thought I read something about that but it seemed to be a CLA just for contributing to GitHub.

**Comment by JesseTG** [comment]
There's no formal mechanism, but you could [write a pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) that contains the CLA, and that by submitting the PR they agree to abide by it.  If they don't agree, don't accept the PR.  As for what the CLA itself should contain?  ...I don't know enough about them to give good advice.  I'd look for a template written by someone who does.

**Comment by louis-langholtz** [comment]
@JesseTG I really appreciate your suggestion about templates! I didn't know anything about those. They look like they'll be super helpful.

BTW, I'd love help with this! :)

**Comment by louis-langholtz** [comment]
I've migrated the development of this code over to my [PlayRho](https://github.com/louis-langholtz/PlayRho) repository and have created the ["Want a pull request template"](https://github.com/louis-langholtz/PlayRho/issues/3) issue there for supporting pull request contributions. Closing this issue in this repo now and hoping people will follow the code's evolution at the new repo.

**Comment by louis-langholtz** [comment]
This issue was moved to louis-langholtz/PlayRho#13
