### ISSUE TITLE
Testbed CMake build option and related code needs help.

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/Box2D#21]
From a report by @Megaxela : "I tried to build testbed and realized that some CMakeLists in project deprecated a little".

While I've updated the CMakeLists for the continuous integration (CI) build, I haven't updated the CMakeLists files that aren't used by the CI build. So these other CMakeLists files very probably do need to be updated.

**Comment by louis-langholtz** [comment]
Commit dbe45c95d12e0f6ccfc4a3919260809b6e62e3c8 updates the Box2D/Testbed/CMakeLists.txt file so it includes files via glob inclusion instead of hard coded paths of every file. Hopefully that helps matters for all platforms.

**Comment by louis-langholtz** [comment]
Looks like issue #34 is related to this.

**Comment by louis-langholtz** [comment]
I'm of the opinion that building the Testbed via CMake still could use help. I've made significant changes to the way the Testbed builds in order to remedy problems that have been reported and which I've seen, but at the same time these probably introduce new issues.

I'd like to get feedback from anyone who tries to build the Testbed via CMake under Linux and hear if that's working for them now or not. I'd also like to get feedback on people's experiences with installing the now externally required GLEW2 and GLFW3 libraries.

I also haven't gotten CMake to work very well for me when building under Visual Studio 2017. It works fine enough to build the physics engine library and the HelloWorld application but then I run into linker issues with different linker options being used between the physics engine library at the Testbed or the Unit Test applications under Windows.

I plan to continue working on these things but input from others will be appreciated!

**Comment by louis-langholtz** [comment]
@Megaxela I believe I've updated all of the CMakeLists.txt files in the project such that none should be deprecated anymore. I'd love it if you're able to confirm this!

Also, I'm taking the bug label off for the moment from this issue since I believe I've fixed these enough so they're not bugged for me when building on Travis.

**Comment by Megaxela** [comment]
Ok, I'll check em, when I'll find some time for it.

**Comment by Megaxela** [comment]
Ok, I finally got some time to check if Box2D will build, and ye, it's building perfect now. 
I guess issue can be closed for now.

**Comment by louis-langholtz** [comment]
Woot!
