### ISSUE TITLE
Why is this repo using glfw and glew libraries inside project? 

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/Box2D#22]
When I was intended to build testbed I just made changed testbed CMakeLists a little (pull request will be soon) and compiled it with my glfw and glew libraries. Ye, I had to change some `#include` directions, but after that everything was fine. It worked. But when I tried to build "examples" with main CMakeLists I got glfw error `#error "No supported window creation API selected"`. I tried to workaround this error by adding couple of `#define` in config.h but it didn't help. So my main question is why are you using glew and glfw source code inside project even if it doesn't work? 
I guess good solution is to remove them, and use external versions, built by linux repos or by manual building.

**Comment by louis-langholtz** [comment]
The use of glew and glfw source code inside the project comes from Erin's Box2D sources that I had forked from where it had this to begin with. I'm sorry that these aren't working for you. I haven't ran into this problem myself but I haven't been building the Testbed under Linux (I do build and use the Testbed a lot however just not under linux). I'd really like the Testbed to build under linux too though.

I've seen some discussion of others having problems with glew and glfw when building Erin's Box2D under linux. The most interesting of which had the suggestion of using a different mechanism than including the sources directly in the Box2D distribution. Git sub-modules seemed to be a suggested way. I use Git sub-modules for the Google Test code and I'd prefer using git-submodules over keeping the glew and glfw sources right in this fork.

Do you think using external versions built by linux repos would be better than using git submodules? I don't have a strong opinion on one solution over the other but cross-platform convenience is an appealing goal to me of any changes in this regard.

**Comment by Megaxela** [comment]
Ye, you know, I forgot about git submodules. I guess the best solutions for now are: Using git submodules or use CMake's ExternalProject. 
But I guess include libraries that will be used in CMakeLists has to be standard, because why must am I download another package if I already has it in my system?

**Comment by louis-langholtz** [comment]
Regarding glew and glfw, I've been wondering how useful are these libraries anyway?

I mean I like having a GUI Testbed but would it be better to redo the Testbed's implementation to use other libraries? Like Qt? Not sure if Qt could fully replace those two but like if Qt is more standard, then maybe it should. Or whatever other library is more standard. I started looking into using Qt at one point and then decided to put that on hold on account of the GUI Testbed not seeming as important as the base Box2D library itself. Perhaps beyond the HelloWorld and unit test applications of Box2D, any other stuff should be a completely separate project.

What are your thoughts on this?

**Comment by Megaxela** [comment]
I dont know. Cause changing API from glew and glfw to Qt needs a lot of changes. And result testbed binary will need pretty heavy Qt libaries.

**Comment by louis-langholtz** [comment]
I've been looking into this more. I too would prefer that GLFW and GLEW not be inside the project.

I've noticed that this project shows up on GitHub as primarily C-language based. I suspect that's because of GLFW and GLEW being primarily C. So chucking these sources out from the project I believe would help this project be recognized more as a C++ project which I'd prefer.

Greater flexibility to pick the releases of GLFW and GLEW would also be a plus IMO.

**Comment by louis-langholtz** [comment]
Just updated the GLFW code that's inside this library from 3.0 to the same 3.1 GLFW code that Erin has now in his master branch of his Box2D repo. I wanted to see how hard using new GLFW sources would be and figured upgrading the in-repo sources just to 3.1 would be an easier first step with less risk. Hopefully that doesn't cause anyone any new problems.

I also downloaded, built, and externally installed the latest GLFW and GLEW libraries.

Between pulling these sources in as git submodules or externally linking to them I'm now leaning towards the latter.

**Comment by louis-langholtz** [comment]
I've removed all the GLEW and GLFW source code from the project now. CMake is now including and linking to external builds of those at least on the CI server linux system.

Some things I haven't done yet but that are on my list:

Haven't tried building via this new CMake setup on any platform besides Linux yet. I haven't updated any build instructions yet though except for the Travis-CI configuration file. The Xcode project file does it the new way now too though it similarly will also need some updated instructions and tweaking by individuals.

Also, there's some related issues to this: issue #34 and issue #21.

**Comment by louis-langholtz** [comment]
I'm not sure that removing the GLFW and GLEW library headers and sources is a win. Seems like it makes building the Testbed harder now in some ways at least for the first build. It does get this project to show up as a primarily C++ source code project now though which I definitely prefer. I believe it also makes it easier now to switch between different releases of GLFW3 or GLEW2 although I don't know that anyone cares about that. It also seemed there's scant Linux repo support for these releases of these libraries so they'll probably need to be built manually by many Linux users.

I'm going to close this issue now on account of these libraries no longer being inside the project and keep my fingers crossed that I don't come to regret removing them.

If you pull the latest sources for this fork and try building the Testbed, I'd very much like to know how that goes for you. If you have problems building it though, let's open a separate issue specific to the trouble you encounter or use one of the other Testbed related issues if they're close enough.
