### ISSUE TITLE
missing underscore on windows with gcc

### ISSUE THREAD

**Issue by gotocoffee1** [louis-langholtz/Box2D#25]
Hey i really like the changes you made, good work^^
But can't compile on windows with gcc. The compiler does not recognize the WIN32 macro 
`#ifndef WIN32 // should be  #ifndef _WIN32`
or am i missing something?

**Comment by louis-langholtz** [comment]
@gotocoffee1 Hmm... interesting. I didn't realize this. I'd gotten things to build under Windows with the define as it is. But I believe you. I'm looking into this.

**Comment by louis-langholtz** [comment]
@gotocoffee1 BTW, what version of gcc are you trying to build with on Windows (or which do you want to build with on Windows)? I'd used MS Visual Studio 2017 C++.

**Comment by louis-langholtz** [comment]
The changes I've committed so far replaced `WIN32` with `_WIN32` everywhere in the Box2D library code.

The macro is still used in GLFW code in a couple places. I want to deal with the GLFW code separately however as it only applies to building the Testbed and I want to update the GLFW code anyway. Made issue #26 for that.
