### ISSUE TITLE
Trying to run CMake on glfw results in an error

### ISSUE THREAD

**Issue by JesseTG** [louis-langholtz/Box2D#34]
This one, specifically.

```
jesse@jesse-ubuntu ~/c/l/B/glfw> cmake .
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
You have called ADD_LIBRARY for library glfw without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error: Cannot determine link language for target "glfw".
CMake Error: CMake can not determine linker language for target: glfw
-- Generating done
-- Build files have been written to: /home/jesse/code/louis-langholtz-Box2D/Box2D/glfw
jesse@jesse-ubuntu ~/c/l/B/glfw>
```

A `Makefile` is generated, but trying to build with it results in this:

```
jesse@jesse-ubuntu ~/c/l/B/glfw> make -j8
make[2]: *** No rule to make target 'CMakeFiles/glfw.dir/build'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/glfw.dir/all' failed
make[1]: *** [CMakeFiles/glfw.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
jesse@jesse-ubuntu ~/c/l/B/glfw> 
```

This is on Ubuntu 16.10.

**Comment by louis-langholtz** [comment]
Thank you for this information. I'd really like to make it easier to build the Testbed on all platforms especially with CMake. So this is useful to know. I think this is a similar failure signature as had been occurring with Erin's Box2D master branch. I don't recall doing much to this particular CMake file so it may well be the same issue as people had been having with Erin's branch.

I can get the Testbed to build with the current MS Visual Studio Solution file and with the current Xcode project file. I haven't gotten the CMake system to work to build more than the Box2D library on Windows. It does build both the Box2D library and the unit test application for me on Linux but I haven't tried getting it to build the Testbed also on Linux.

Looking at your command prompt, I take it that this occurred on a Ubuntu Linux system then. I'll make building the Testbed on Linux with CMake a higher priority then than getting the Testbed building on Windows with CMake (it already builds with MS VS Solution at least).

**Comment by JesseTG** [comment]
I can help you out with this after I finish finals next week.

**Comment by louis-langholtz** [comment]
I think I got all targets build-able now using CMake on Linux. At least the CI system is building all now. Among other things, I removed all the GLEW and GLFW source code from the project and am now including and linking to external builds of those. I haven't updated any build instructions yet though except for the Travis-CI configuration file.

**Comment by louis-langholtz** [comment]
Building the Testbed is now a matter of first installing the GLEW2 and GLFW3 project header files and binary libraries. If there's a Linux package server that has these for installation as an `apt`, `rpm` or something package, then all the better.

Once those and any of their dependencies are resolved, then the Testbed should be build-able via the `cmake -DBOX2D_BUILD_TESTBED=ON <CMakefile-path> && make` sequence.

There's a `README` file in the `Testbed` directory now that explains this too.

**Comment by louis-langholtz** [comment]
Closing this issue since it's no longer relevant because of GLEW2 and GLFW3 sources having been removed from the project.

In a separate issue that provides the new specifics, please let me know what problems, if any, you encounter on trying to build the Testbed now. Make sure to pull the latest sources first of course.
