### ISSUE TITLE
Add ability to rename this project in the CMake file

### ISSUE THREAD

**Issue by JesseTG** [louis-langholtz/Box2D#35]
Reason is that I want to have both stock Box2D and this installed on my computer.  I want to use this for my projects, but I also want to keep stock Box2D around to build existing codebases.  So I can link this as `-lBox2D-louis` or something.

**Comment by louis-langholtz** [comment]
Thanks for opening this issue! Sounds like something that'd be useful to have.

Any suggestions on how to do this? Is this something that CMake has support for? I'll look into these things but if you have some experience with this already I'd love to benefit from it.

As maybe an alternative, what do you think about me just outright renaming this project? Like from Box2D to something else? I've been considering this but haven't come to a decision yet.

**Comment by JesseTG** [comment]
> Any suggestions on how to do this? Is this something that CMake has support for? I'll look into these things but if you have some experience with this already I'd love to benefit from it.

Yes, you can do that in the same way you specify any CMake variable; `LOUIS_BOX2D_PREFIX` or something.

> As maybe an alternative, what do you think about me just outright renaming this project? Like from Box2D to something else? I've been considering this but haven't come to a decision yet.

Personally, that's what I would *actually* do, but I wasn't sure if you would be receptive to it.  But you suggested it before I did, so I guess there's no issue.

**Comment by louis-langholtz** [comment]
Sorry it's been a while since I last commented on this issue. I've been giving it thought this whole time though towards outright renaming the project. I'm admittedly stuck on what to call it. I don't want to use a name that's tied to particular functionality since I don't want functionality to be restrained. I'd like a name that sounds playful and fun. So that's where this issue is, at the moment.

**Comment by louis-langholtz** [comment]
Done now. I chose to rename the project to [PlayRho](https://github.com/louis-langholtz/PlayRho). I'll be continuing development over there from now on. Hope the new name sounds okay to you.

At the new project almost everything should now have the following translations done:

- `Box2D` should now appear as `PlayRho`.
- `BOX2D` should now appear as `PLAYRHO`.
- `box2d` should now appear as `playrho`.
